title: TRC Trinity Documentation
description: The official documentation website for products sold by TRC Trinity.
theme: just-the-docs

url: docs.trctrinity.com
aux_links_new_tab: false

aux_links:
  Github Repository: https://github.com/TRC-Trinity/Documentation
  TRC Trinity Home: trctrinity.com
