#name: TRC Trinity Documentation
#title: TRC Trinity Documentation
logo: "/assets/images/just-the-docs.png"
description: The official documentation website for products sold by TRC Trinity.
url: docs.trctrinity.com

theme: just-the-docs
color_scheme: TRCTrinity

search_enabled: true
search.button: true

aux_links_new_tab: false
aux_links:
  Github Repository: https://github.com/TRC-Trinity/Documentation
  TRC Trinity Home: https://trctrinity.com
